<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.Http.Authentication\jaytwo.Http.Authentication.csproj" />
    <ProjectReference Include="..\BasicAuthSampleApp\BasicAuthSampleApp.csproj" />
    <ProjectReference Include="..\BearerAuthSampleApp\BearerAuthSampleApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="jaytwo.SolutionResolution" Version="0.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.19" />
  </ItemGroup>

</Project>
