<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jakegough/jaytwo.Http.Authentication.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="jaytwo.Http" Version="0.1.0-*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jaytwo.Http.Authentication.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>

</Project>
